{{- range .Values.mayastorPools }}
---
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  # Name can be anything as long as it is unique
  # or let k8s to generate a unique pool name
  # if you use namePrefix, eg pool-
  {{- if .namePrefix }}
  generateName: {{ .namePrefix | quote }}
  {{- else }}
  name: pool-on-{{ .node }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
spec:
  node: {{ .node }}
  # ATM only one disk device is supported (i.e. /dev/nvme1n1)
  disks: ["{{ .device }}"]
{{- end }}